GET http://localhost:3001/workouts/1
Content-Type: application/json

{
    "name": "Lower Body B",
    "date": "2026-03-14",
    "exercises": [
        {
            "exerciseId": 1,
            "sets": [
                { "reps": 10, "weight": 185 }
            ]
        }
    ]

}
